modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/ASangarin/AriKeys/issues"
license = "MIT"

[[mods]]
modId = "arikeys"
version = "${version}"
displayName = "AriKeys"
authors = "ASangarin"
description = '''
Allows the Minecraft client to send AriKey keypresses to the server.
'''
logoFile = "icon.png"

[[dependencies.arikeys]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.arikeys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.arikeys]]
modId = "architectury"
mandatory = true
versionRange = "[10.1.20,)"
ordering = "AFTER"
side = "CLIENT"
