modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ASangarin/AriKeys/issues"
license = "MIT"

[[mods]]
modId = "arikeys"
version = "${version}"
displayName = "AriKeys"
authors = "ASangarin"
description = '''
Allows the Minecraft client to send AriKey keypresses to the server.
'''
logoFile = "icon.png"

[[dependencies.arikeys]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.arikeys]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "arikeys.mixins.json"
[[mixins]]
config = "arikeys-neoforge.mixins.json"